### ISSUE TITLE
Parse responses to get 2 new files

### ISSUE THREAD

**Issue by ceh-2000** [ceh-2000/KBAfiles#1]
## Description
We want to append the scoping information to the uploaded files. 

## Tasks
- [ ] If files are uploaded, append the response for each polygon/multi-polygon to the original geopandas dataframe. Download the result as a geopkg.
- [x] Put the JSON taxas into a separate CSV (fields should be the same so this should work).
- [ ] Determine the two additional files that need to be returned with each item.
- [ ] Dump new files in a Google Cloud bucket and return the paths to the files of interest https://cloud.google.com/storage/docs/uploading-objects#prereq-code-samples. You may need to use service accounts to get around rules about authentication.
